name: Brim CI

on: [push]

jobs:
  advance-zq:
    name: Advance ZQ
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-18.04]
    steps:
      # Only one of these should run at a time, and the checkout of brim
      # has to be in the "protected section".
      - name: Turnstyle
        uses: softprops/turnstyle@v0.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: sleep 60
      - uses: actions/checkout@v2
      - run: git config --local user.email 'automation@brimsecurity.com'
      - run: git config --local user.name 'Brim Automation'
      - run: date > a
      - run: git add a
      - run: git commit -a -m "update $(date)"
      - run: git push "https://${GITHUB_ACTOR}:${{ secrets.ZQ_UPDATE_PAT }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:fake-master-for-zq-updates
